/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 *
 * Generated by: https://openapi-generator.tech
 */

use async_trait::async_trait;
use std::option::Option;
use std::{borrow::Borrow, sync::Arc};

use reqwest;

use crate::errors::errors::WorkflowError;

use super::configuration;

pub struct EngineApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl EngineApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> EngineApiClient {
        EngineApiClient { configuration }
    }
}

#[async_trait]
pub trait EngineApi {
    async fn get_process_engine_names(
        &self,
    ) -> Result<Vec<crate::models::ProcessEngineDto>, WorkflowError>;
}

#[async_trait]
impl EngineApi for EngineApiClient {
    async fn get_process_engine_names(
        &self,
    ) -> Result<Vec<crate::models::ProcessEngineDto>, WorkflowError> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/engine", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let resp = req_builder.send().await?;

        Ok(resp.error_for_status()?.json().await?)
    }
}
